Address Hayley and Andy feedback
USGS-R/lake-temp-lstm-static-data-release pull request #32
Opened 2023-03-02 22:40 UTC by lindsayplatt

Hayley and Andy gave minor feedback in #28. This PR addresses it! It does not close that issue as there will be more feedback coming. (@hcorson-dosch-usgs I would like you to review as well, but it won't let me add your user as an official reviewer for some reason).

- [X] explicitly state somewhere that these same depth intervals were used for the exported temperature predictions, including those generated by GLM (from @hcorson-dosch-usgs)
- [X] note somewhere the exact version of GLM used - GLM version 3.2.0a8 (from @hcorson-dosch-usgs)
- [X] update the description of the included files that goes along with the field shown as `Type: webLink` (from @AndyMcAliley)

Not relevant anymore BUT I did originally manually upload the updated XML from these metadata changes due to a limitation with slow HPC processes timing out my authentication before the upload could happen. I manually uploaded so that I could lock the item and send to Jordan for a review. He has reviewed and HPC is back to normal, so I unlocked the item and re-ran `scmake()` to push the updated XML with the pipeline today.

2023-03-03 00:19 UTC, AndyMcAliley requested changes
This works from the perspective of describing the LSTM output! I'll let Hayley comment on the GLM perspective. My only suggested change regards the numbers of zip files.

2023-03-03 00:19 UTC, AndyMcAliley commented on in_text/text_data_release.yml
> +file-format: Five comma-delimited files, one zipped shapefile, nine zip files containing comma-delimited files, ten zip files containing netCDF files, two R scripts, and a single PNG file
I counted ten zip files containing csvs (nine meteorological driver zips plus lake_temperature_observations.zip) and nine zip files containing netCDF files.

2023-03-03 00:19 UTC, AndyMcAliley commented on in_text/text_data_release.yml
> +file-format: Five comma-delimited files, one zipped shapefile, nine zip files containing comma-delimited files, ten zip files containing netCDF files, two R scripts, and a single PNG file
```suggestion
file-format: Five comma-delimited files, one zipped shapefile, ten zip files containing comma-delimited files, nine zip files containing netCDF files, two R scripts, and a single PNG file
```

2023-03-03 14:56 UTC, lindsayplatt commented on in_text/text_data_release.yml
> +file-format: Five comma-delimited files, one zipped shapefile, nine zip files containing comma-delimited files, ten zip files containing netCDF files, two R scripts, and a single PNG file
Oh! Thanks for counting those. You are right!

2023-03-03 14:57 UTC, lindsayplatt commented on in_text/text_data_release.yml
> +file-format: Five comma-delimited files, one zipped shapefile, nine zip files containing comma-delimited files, ten zip files containing netCDF files, two R scripts, and a single PNG file
Wait, just kidding! I thought about it for a second more and remembered why the numbers are what they are. The `meteorological_inputs_GCM.zip` contains NetCDFs, not CSVs.

2023-03-03 20:10 UTC, AndyMcAliley commented on in_text/text_data_release.yml
> +file-format: Five comma-delimited files, one zipped shapefile, nine zip files containing comma-delimited files, ten zip files containing netCDF files, two R scripts, and a single PNG file
Aha, great catch! Sorry I mislead you.

2023-03-03 20:11 UTC, AndyMcAliley approved these changes

2023-03-06 21:38 UTC, hcorson-dosch-usgs approved these changes
I just had one suggested edit for clarity re: the depth discretization

2023-03-06 21:38 UTC, hcorson-dosch-usgs commented on in_text/text_data_release.yml
> +  In this data release, lakes were discretized into a series of depth intervals for modeling input/output. The top 10 meters of the lake were discretized
My only hesitation with this statement is that I don't want to suggest that we somehow parameterized GLM for select depth intervals, since it ran w/ variable Lagrangian layers (as you note below) and produced predictions at 0.5-m intervals. For the GLM work, it would be more accurate to say that we exported predictions at a series of depth intervals. Maybe you could specify something like 'lakes were discretized into a series of depth intervals for EALSTM model input/output... etc.' and then tack a sentence at the end like 'These same depth intervals were used for GLM output'

2023-03-20 17:37 UTC, merged